### ISSUE TITLE
Error Cannot resolve 'airflow.utils.log.es_task_handler.ElasticsearchTaskHandler': No module named 'elasticsearch'

### ISSUE THREAD

**Issue by carloscorreiafinanto** [slatawa/Airflow-Monitoring-ElasticSearch-LogStash-Kibana#1]
After execute docker-compose -f .\docker-compose-log-stack.yml up -d
[+] Running 10/10
 ✔ Network airflow-monitoring-elasticsearch-logstash-kibana_default            Created                                                                                                                                                 0.0s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-redis-1          Started                                                                                                                                                 1.0s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-postgres-1       Started                                                                                                                                                 1.1s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-flower-1         Started                                                                                                                                                 1.4s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-webserver-1      Started                                                                                                                                                 1.7s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-scheduler-1      Started                                                                                                                                                 2.1s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-worker-1         Started                                                                                                                                                 2.4s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-elasticsearch-1  Started                                                                                                                                                 2.8s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-kibana-1         Started                                                                                                                                                 3.5s
 ✔ Container airflow-monitoring-elasticsearch-logstash-kibana-logstash-1       Started

I received this error when webserver try to up :

023-04-06 13:27:23 ValueError: Unable to configure handler 'task'
2023-04-06 13:27:24 WARNING:root:/usr/local/airflow/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
2023-04-06 13:27:24 WARNING:airflow.logging_config:Unable to load the config, contains a configuration error.
2023-04-06 13:27:24 Traceback (most recent call last):
2023-04-06 13:27:24   File "/usr/local/lib/python3.7/logging/config.py", line 388, in resolve
2023-04-06 13:27:24     found = getattr(found, frag)
2023-04-06 13:27:24 AttributeError: module 'airflow.utils.log' has no attribute 'es_task_handler'
2023-04-06 13:27:24 
2023-04-06 13:27:24 During handling of the above exception, another exception occurred:
2023-04-06 13:27:24 
2023-04-06 13:27:24 Traceback (most recent call last):
2023-04-06 13:27:24   File "/usr/local/lib/python3.7/logging/config.py", line 390, in resolve
2023-04-06 13:27:24     self.importer(used)
2023-04-06 13:27:24   File "/usr/local/lib/python3.7/site-packages/airflow/utils/log/es_task_handler.py", line 21, in <module>
2023-04-06 13:27:24     import elasticsearch
2023-04-06 13:27:24 ModuleNotFoundError: No module named 'elasticsearch'
2023-04-06 13:27:24 
2023-04-06 13:27:24 The above exception was the direct cause of the following exception:
2023-04-06 13:27:24 
2023-04-06 13:27:24 Traceback (most recent call last):
2023-04-06 13:27:24   File "/usr/local/lib/python3.7/logging/config.py", line 563, in configure
2023-04-06 13:27:24     handler = self.configure_handler(handlers[name])
2023-04-06 13:27:24   File "/usr/local/lib/python3.7/logging/config.py", line 713, in configure_handler
2023-04-06 13:27:24     klass = self.resolve(cname)
2023-04-06 13:27:24   File "/usr/local/lib/python3.7/logging/config.py", line 397, in resolve
2023-04-06 13:27:24     raise v
2023-04-06 13:27:24   File "/usr/local/lib/python3.7/logging/config.py", line 390, in resolve
2023-04-06 13:27:24     self.importer(used)
2023-04-06 13:27:24   File "/usr/local/lib/python3.7/site-packages/airflow/utils/log/es_task_handler.py", line 21, in <module>
2023-04-06 13:27:24     import elasticsearch
2023-04-06 13:27:24 ValueError: Cannot resolve 'airflow.utils.log.es_task_handler.ElasticsearchTaskHandler': No module named 'elasticsearch'

**Comment by giannisyp** [comment]
same error for me as well
